import 'package:flutter/material.dart';

import 'app_colors.dart';

class ColorPalette {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff00C076),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD4E3FF),
    onPrimaryContainer: Color(0xFF001C3A),
    secondary: AppColors.accentColor,
    onSecondary: AppColors.accentColor,
    secondaryContainer: Color(0xFFD4E3FF),
    onSecondaryContainer: Color(0xFF001C39),
    tertiary: Color(0xFF006398),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFCDE5FF),
    onTertiaryContainer: Color(0xFF001D32),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFAFCFF),
    onBackground: Color(0xFF001F2A),
    surface: Color(0xFFFAFCFF),
    onSurface: Color(0xFF001F2A),
    surfaceVariant: Color(0xFFE0E2EB),
    onSurfaceVariant: Color(0xFF43474E),
    outline: Color(0xFF74777F),
    onInverseSurface: Color(0xFFE1F4FF),
    inverseSurface: Color(0xFF003547),
    inversePrimary: Color(0xFFA4C8FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF195FA7),
    outlineVariant: Color(0xFFC3C6CF),
    scrim: Color(0xFF000000),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff00C076),
    onPrimary: Color(0xffA7B1BC),
    primaryContainer: Color(0xff17181B),
    onPrimaryContainer: Colors.white,
    secondary: AppColors.accentColor,
    onSecondary: Color(0xFF00315D),
    secondaryContainer: Color(0xFF004883),
    onSecondaryContainer: Color(0xFFD4E3FF),
    tertiary: Color(0xFF94CCFF),
    onTertiary: Color(0xFF003352),
    tertiaryContainer: Color(0xFF004B74),
    onTertiaryContainer: Color(0xFFCDE5FF),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xff17181B),
    onBackground: Color(0xff17181B),
    surface: Color(0xFF001F2A),
    onSurface: Colors.white,
    surfaceVariant: Color(0xFF43474E),
    onSurfaceVariant: Color(0xFFC3C6CF),
    outline: Color(0xFF8D9199),
    onInverseSurface: Color(0xFF001F2A),
    inverseSurface: Color(0xFFBFE9FF),
    inversePrimary: Color(0xFF195FA7),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFA4C8FF),
    outlineVariant: Color(0xFF43474E),
    scrim: Color(0xFF000000),
  );
}
