/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String angle_down = "assets/svgs/angle_down.svg";
  static const String arrow_down = "assets/svgs/arrow_down.svg";
  static const String box = "assets/svgs/box.svg";
  static const String btc = "assets/pngs/btc.png";
  static const String candle_chart = "assets/svgs/candle_chart.svg";
  static const String clock = "assets/svgs/clock.svg";
  static const String down = "assets/svgs/down.svg";
  static const String expand = "assets/svgs/expand.svg";
  static const String globe = "assets/svgs/globe.svg";
  static const String info = "assets/svgs/info.svg";
  static const String logo = "assets/pngs/logo.png";
  static const String Logomark = "assets/pngs/Logomark.png";
  static const String menu = "assets/svgs/menu.svg";
  static const String order_chart_one = "assets/svgs/order_chart_one.svg";
  static const String order_chart_three = "assets/svgs/order_chart_three.svg.svg";
  static const String order_chart_two = "assets/svgs/order_chart_two.svg.svg";
  static const String profile = "assets/pngs/profile.png";
  static const String Satoshi_Black = "assets/fonts/Satoshi-Black.otf";
  static const String Satoshi_Bold = "assets/fonts/Satoshi-Bold.otf";
  static const String Satoshi_BoldItalic = "assets/fonts/Satoshi-BoldItalic.otf";
  static const String Satoshi_Italic = "assets/fonts/Satoshi-Italic.otf";
  static const String Satoshi_Light = "assets/fonts/Satoshi-Light.otf";
  static const String Satoshi_LightItalic = "assets/fonts/Satoshi-LightItalic.otf";
  static const String Satoshi_Medium = "assets/fonts/Satoshi-Medium.otf";
  static const String Satoshi_MediumItalic = "assets/fonts/Satoshi-MediumItalic.otf";
  static const String Satoshi_Regular = "assets/fonts/Satoshi-Regular.otf";
  static const String up = "assets/svgs/up.svg";
}
